export const defaultCities = [
  { name: "Vancouver", country: "Canada", timezone: "America/Vancouver", abbreviation: "PDT", flag: "🇨🇦", image: "/vancouver.png" },
  { name: "Ottawa", country: "Canada", timezone: "America/Toronto", abbreviation: "EDT", flag: "🇨🇦", image: "/ottawa.png" },
  { name: "Bangkok", country: "Thailand", timezone: "Asia/Bangkok", abbreviation: "ICT", flag: "🇹🇭", image: "/bkk.png" },
  { name: "Ho Chi Minh City", country: "Vietnam", timezone: "Asia/Ho_Chi_Minh", abbreviation: "ICT", flag: "🇻🇳", image: "/hcmc.png" },
  { name: "Kuala Lumpur", country: "Malaysia", timezone: "Asia/Kuala_Lumpur", abbreviation: "MYT", flag: "🇲🇾", image: "/kl.png" },
  { name: "Singapore", country: "Singapore", timezone: "Asia/Singapore", abbreviation: "SGT", flag: "🇸🇬", image: "/singapore.png" },
  { name: "Jakarta", country: "Indonesia", timezone: "Asia/Jakarta", abbreviation: "WIB", flag: "🇮🇩", image: "/jakarta.png" },
  { name: "Manila", country: "Philippines", timezone: "Asia/Manila", abbreviation: "PHT", flag: "🇵🇭", image: "/manila.png" },
  { name: "Taipei", country: "Taiwan", timezone: "Asia/Taipei", abbreviation: "CST", flag: "🇹🇼", image: "/taipei.png" },
  { name: "Tokyo", country: "Japan", timezone: "Asia/Tokyo", abbreviation: "JST", flag: "🇯🇵", image: "/tokyo.png" },
  { name: "Colombo", country: "Sri Lanka", timezone: "Asia/Colombo", abbreviation: "IST", flag: "🇱🇰", image: "/colombo.png" },
  { name: "Dubai", country: "United Arab Emirates", timezone: "Asia/Dubai", abbreviation: "GST", flag: "🇦🇪", image: "/dubai.png" },
  { name: "Amman", country: "Jordan", timezone: "Asia/Amman", abbreviation: "EET", flag: "🇯🇴", image: "/amman.png" },
  { name: "Beirut", country: "Lebanon", timezone: "Asia/Beirut", abbreviation: "EET", flag: "🇱🇧", image: "/beirut.png" },
  { name: "Istanbul", country: "Turkey", timezone: "Europe/Istanbul", abbreviation: "EET", flag: "🇹🇷", image: "/istanbul.png" },
  { name: "Bucharest", country: "Romania", timezone: "Europe/Bucharest", abbreviation: "EET", flag: "🇷🇴", image: "/bucharest.png" },
  { name: "Luxembourg", country: "Luxembourg", timezone: "Europe/Luxembourg", abbreviation: "CET", flag: "🇱🇺", image: "/luxembourg.png" },
  { name: "Nice", country: "France", timezone: "Europe/Paris", abbreviation: "CET", flag: "🇫🇷", image: "/nice.png" },
  { name: "Barcelona", country: "Spain", timezone: "Europe/Madrid", abbreviation: "CET", flag: "🇪🇸", image: "/barcelona.png" },
  { name: "Lisbon", country: "Portugal", timezone: "Europe/Lisbon", abbreviation: "WET", flag: "🇵🇹", image: "/lisbon.png" },
  { name: "Casablanca", country: "Morocco", timezone: "Africa/Casablanca", abbreviation: "WET", flag: "🇲🇦", image: "/casablanca.png" },
  { name: "London", country: "United Kingdom", timezone: "Europe/London", abbreviation: "BST", flag: "🇬🇧", image: "/london.png" },
  { name: "New York", country: "United States", timezone: "America/New_York", abbreviation: "EDT", flag: "🇺🇸", image: "/ny.png" },
]